# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
box: arista/veos
interfaces:
- ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.26/30
  linkindex: 7
  name: sfp51 -> dis51
  neighbors:
  - ifname: Ethernet4
    ipv4: 10.1.0.25/30
    node: dis51
  remote_id: 6
  remote_ifindex: 4
  type: p2p
- ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.30/30
  linkindex: 8
  name: sfp51 -> sfp01
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.29/30
    node: sfp01
  remote_id: 1
  remote_ifindex: 2
  type: p2p
- ifindex: 3
  ifname: Ethernet3
  ipv4: 10.1.0.38/30
  linkindex: 10
  name: sfp51 -> ser02
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.37/30
    node: ser02
  remote_id: 9
  remote_ifindex: 2
  type: p2p
loopback:
  ipv4: 10.0.0.2/32
mgmt:
  ifname: Management1
  ipv4: 192.168.121.102
  mac: 08-4F-A9-00-00-02
