name: netsim-ceos-mcast_a

topology:
  nodes:
    sfp01:
      kind: ceos
      image: ceos:4.27.0F

    sfp51:
      kind: ceos
      image: ceos:4.27.0F

    sfc01:
      kind: ceos
      image: ceos:4.27.0F

    sfc51:
      kind: ceos
      image: ceos:4.27.0F

    dis01:
      kind: ceos
      image: ceos:4.27.0F

    dis51:
      kind: ceos
      image: ceos:4.27.0F

    edz:
      kind: ceos
      image: ceos:4.27.0F

    ser01:
      kind: ceos
      image: ceos:4.27.0F

    ser02:
      kind: ceos
      image: ceos:4.27.0F

    ser03:
      kind: ceos
      image: ceos:4.27.0F



  links:
  - endpoints:
    - "sfc01:eth1"
    - "dis01:eth1"
  - endpoints:
    - "dis01:eth2"
    - "dis51:eth1"
  - endpoints:
    - "dis01:eth3"
    - "edz:eth1"
  - endpoints:
    - "sfp01:eth1"
    - "dis01:eth4"
  - endpoints:
    - "sfc51:eth1"
    - "dis51:eth2"
  - endpoints:
    - "dis51:eth3"
    - "edz:eth2"
  - endpoints:
    - "sfp51:eth1"
    - "dis51:eth4"
  - endpoints:
    - "sfp01:eth2"
    - "sfp51:eth2"
  - endpoints:
    - "sfp01:eth3"
    - "ser02:eth1"
  - endpoints:
    - "sfp51:eth3"
    - "ser02:eth2"
  - endpoints:
    - "sfc01:eth2"
    - "sfc51:eth2"
  - endpoints:
    - "sfc01:eth3"
    - "ser03:eth1"
  - endpoints:
    - "sfc51:eth3"
    - "ser03:eth2"
  - endpoints:
    - "edz:eth3"
    - "ser01:eth1"

