# Ansible inventory created from ['./topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
eos:
  hosts:
    dis01:
      ansible_host: clab-netsim-ceos-mcast_a--dis01
      id: 5
    dis51:
      ansible_host: clab-netsim-ceos-mcast_a--dis51
      id: 6
    edz:
      ansible_host: clab-netsim-ceos-mcast_a--edz
      id: 7
    ser01:
      ansible_host: clab-netsim-ceos-mcast_a--ser01
      id: 8
    ser02:
      ansible_host: clab-netsim-ceos-mcast_a--ser02
      id: 9
    ser03:
      ansible_host: clab-netsim-ceos-mcast_a--ser03
      id: 10
    sfc01:
      ansible_host: clab-netsim-ceos-mcast_a--sfc01
      id: 3
    sfc51:
      ansible_host: clab-netsim-ceos-mcast_a--sfc51
      id: 4
    sfp01:
      ansible_host: clab-netsim-ceos-mcast_a--sfp01
      id: 1
    sfp51:
      ansible_host: clab-netsim-ceos-mcast_a--sfp51
      id: 2
