# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65002
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65003
    ifindex: 1
    ipv4: 10.1.0.6
    name: r3
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.3
box: ceos:4.27.3F
clab:
  env:
    INTFTYPE: et
  kind: ceos
hostname: clab-netsim-ceos-flowpec_a-r2
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.5/30
  linkindex: 2
  name: r2 -> r3
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.6/30
    node: r3
  remote_id: 4
  remote_ifindex: 2
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: netsim-br_5
  clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 172.16.1.3/24
  linkindex: 5
  name: r2 -> [serverb]
  neighbors:
  - ifname: eth1
    ipv4: 172.16.1.6/24
    node: serverb
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: true
  role: stub
  type: lan
loopback:
  ipv4: 10.0.0.3/32
mgmt:
  ifname: Management0
  ipv4: 192.168.121.103
  mac: 08-4F-A9-00-00-03
module:
- ospf
- bgp
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.3
