# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65001
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65000
    ifindex: 1
    ipv4: 10.1.0.6
    name: rr
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.2
box: networkop/cx:4.3.0
clab:
  kind: cvx
hostname: clab-netsim-ceos-flowpec_b-r1
interfaces:
- ifindex: 1
  ifname: swp1
  ipv4: 10.1.0.5/30
  linkindex: 2
  mtu: 1500
  name: r1 -> rr
  neighbors:
  - ifname: swp2
    ipv4: 10.1.0.6/30
    node: rr
  remote_id: 1
  remote_ifindex: 2
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: netsim-br_3
  ifindex: 2
  ifname: swp2
  ipv4: 172.16.0.2/24
  linkindex: 3
  mtu: 1500
  name: r1 -> [servera]
  neighbors:
  - ifname: eth1
    ipv4: 172.16.0.4/24
    node: servera
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: true
  role: stub
  type: lan
loopback:
  ipv4: 10.0.0.2/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.102
  mac: 08-4F-A9-00-00-02
module:
- ospf
- bgp
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.2
runtime: docker
