name: netsim-ceos-mpls_a

topology:
  nodes:
    rr1:
      kind: ceos
      image: ceos:4.27.0F
      group: as65000
    rr2:
      kind: ceos
      image: ceos:4.27.0F
      group: as65000
    pe1:
      kind: ceos
      image: ceos:4.27.0F
      group: as65000
    pe2:
      kind: ceos
      image: ceos:4.27.0F
      group: as65000
    x1:
      kind: ceos
      image: ceos:4.27.0F
      group: as65001
    c11:
      kind: ceos
      image: ceos:4.27.0F
      group: 
    c12:
      kind: ceos
      image: ceos:4.27.0F
      group: 
    c21:
      kind: ceos
      image: ceos:4.27.0F
      group: 
    cx1:
      kind: ceos
      image: ceos:4.27.0F
      group: 
    red1:
      kind: ceos
      image: ceos:4.27.0F
      group: 
    red2:
      kind: ceos
      image: ceos:4.27.0F
      group: 
    blue1:
      kind: ceos
      image: ceos:4.27.0F
      group: 


  links:
  - endpoints:
    - "rr1:eth1"
    - "pe1:eth1"
  - endpoints:
    - "rr1:eth2"
    - "pe2:eth1"
  - endpoints:
    - "rr2:eth1"
    - "pe1:eth2"
  - endpoints:
    - "rr2:eth2"
    - "pe2:eth2"
  - endpoints:
    - "rr1:eth3"
    - "x1:eth1"
  - endpoints:
    - "pe1:eth3"
    - "c11:eth1"
  - endpoints:
    - "pe1:eth4"
    - "c12:eth1"
  - endpoints:
    - "pe2:eth3"
    - "c21:eth1"
  - endpoints:
    - "x1:eth2"
    - "cx1:eth1"
  - endpoints:
    - "c11:eth2"
    - "red1:eth1"
  - endpoints:
    - "c12:eth2"
    - "blue1:eth1"
  - endpoints:
    - "c21:eth2"
    - "red2:eth1"

