# Ansible inventory created from ['./topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
as65000:
  hosts:
    pe1: {}
    pe2: {}
    rr1: {}
    rr2: {}
as65001:
  hosts:
    x1: {}
eos:
  hosts:
    c11:
      ansible_host: clab-netsim-ceos-mpls_a-c11
      id: 10
    c12:
      ansible_host: clab-netsim-ceos-mpls_a-c12
      id: 11
    c21:
      ansible_host: clab-netsim-ceos-mpls_a-c21
      id: 12
    p1:
      ansible_host: clab-netsim-ceos-mpls_a-p1
      id: 5
    p2:
      ansible_host: clab-netsim-ceos-mpls_a-p2
      id: 6
    p3:
      ansible_host: clab-netsim-ceos-mpls_a-p3
      id: 7
    p4:
      ansible_host: clab-netsim-ceos-mpls_a-p4
      id: 8
    p5:
      ansible_host: clab-netsim-ceos-mpls_a-p5
      id: 9
    pe1:
      ansible_host: clab-netsim-ceos-mpls_a-pe1
      id: 3
    pe2:
      ansible_host: clab-netsim-ceos-mpls_a-pe2
      id: 4
    rr1:
      ansible_host: clab-netsim-ceos-mpls_a-rr1
      id: 1
    rr2:
      ansible_host: clab-netsim-ceos-mpls_a-rr2
      id: 2
    x1:
      ansible_host: clab-netsim-ceos-mpls_a-x1
      id: 13
