# Ansible inventory created from ['./topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65002
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - activate:
      ipv4: true
    as: 65002
    ipv4: 10.0.0.3
    name: C
    type: ibgp
  - activate:
      ipv4: true
    as: 65002
    ipv4: 10.0.0.4
    name: D
    type: ibgp
  - activate:
      ipv4: true
    as: 65002
    ipv4: 10.0.0.5
    name: E
    type: ibgp
  - activate:
      ipv4: true
    as: 65002
    ipv4: 10.0.0.6
    name: F
    type: ibgp
  next_hop_self: true
  router_id: 10.0.0.7
box: ceos:4.28.1F
clab:
  env:
    INTFTYPE: et
  kind: ceos
hostname: clab-simple2-G
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.34/30
  linkindex: 9
  name: G -> E
  neighbors:
  - ifname: Ethernet3
    ipv4: 10.1.0.33/30
    node: E
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
- clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.38/30
  linkindex: 10
  name: G -> F
  neighbors:
  - ifname: Ethernet3
    ipv4: 10.1.0.37/30
    node: F
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ipv4: 10.0.0.7/32
mgmt:
  ifname: Management0
  ipv4: 192.168.121.107
  mac: 08-4F-A9-00-00-07
module:
- ospf
- bgp
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.7
