# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65000
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  neighbors: []
  next_hop_self: true
  router_id: 10.0.0.1
  rr: true
  rr_cluster_id: 10.0.0.1
box: networkop/cx:4.3.0
clab:
  kind: cvx
hostname: clab-netsim-ceos-flowpec_a-rr
interfaces:
- ifindex: 1
  ifname: swp1
  ipv4: 10.1.0.2/30
  linkindex: 1
  mtu: 1500
  name: rr -> ixp
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.1/30
    node: ixp
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  remote_id: 2
  remote_ifindex: 1
  type: p2p
loopback:
  ipv4: 10.0.0.1/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08-4F-A9-00-00-01
module:
- ospf
- bgp
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.1
runtime: docker
