# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65000
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65003
    ifindex: 1
    ipv4: 10.1.0.9
    name: r3
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.1
box: networkop/cx:4.3.0
clab:
  kind: cvx
hostname: clab-netsim-ceos-flowpec_a-rr
interfaces:
- ifindex: 1
  ifname: swp1
  ipv4: 10.1.0.10/30
  linkindex: 3
  mtu: 1500
  name: rr -> r3
  neighbors:
  - ifname: Ethernet3
    ipv4: 10.1.0.9/30
    node: r3
  remote_id: 4
  remote_ifindex: 3
  role: external
  type: p2p
loopback:
  ipv4: 10.0.0.1/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08-4F-A9-00-00-01
module:
- bgp
mtu: 1500
runtime: docker
