# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
box: CumulusCommunity/cumulus-vx
box_version: 4.4.0
interfaces:
- ifindex: 1
  ifname: swp1
  ipv4: 10.1.0.14/30
  linkindex: 4
  name: sfp01 -> dis01
  neighbors:
  - ifname: swp4
    ipv4: 10.1.0.13/30
    node: dis01
  remote_id: 5
  remote_ifindex: 4
  type: p2p
- ifindex: 2
  ifname: swp2
  ipv4: 10.1.0.29/30
  linkindex: 8
  name: sfp01 -> sfp51
  neighbors:
  - ifname: swp2
    ipv4: 10.1.0.30/30
    node: sfp51
  remote_id: 2
  remote_ifindex: 2
  type: p2p
- ifindex: 3
  ifname: swp3
  ipv4: 10.1.0.34/30
  linkindex: 9
  name: sfp01 -> ser02
  neighbors:
  - ifname: swp1
    ipv4: 10.1.0.33/30
    node: ser02
  remote_id: 9
  remote_ifindex: 1
  type: p2p
loopback:
  ipv4: 10.0.0.1/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08-4F-A9-00-00-01
