name: netsim-ceos-flowpec_a

topology:
  nodes:
    rr:
      kind: cvx
      image: networkop/cx:4.3.0
      group: as65000
      runtime: docker
      exec:
        - ip link set dev swp1 mtu 1500
        - ip link set dev swp2 mtu 1500
      binds:
        - rr-exabgp-files/exabgp.conf:/exabgp.conf
        - rr-exabgp-files/routes.py:/routes.py

    r1:
      kind: cvx
      image: networkop/cx:4.3.0
      group: as65001
      runtime: docker
      exec:
        - ip link set dev swp1 mtu 1500
        - ip link set dev swp2 mtu 1500
    r2:
      kind: ceos
      image: ceos:4.27.3F
      group: as65002
      env: {'INTFTYPE': 'et'}
    servera:
      kind: linux
      image: alpine
      group:
      exec:
        - ip link set dev eth1 mtu 1500
    serverb:
      kind: linux
      image: alpine
      group:
      exec: 
        - ip link set dev eth1 mtu 1500


  links:
  - endpoints:
    - "rr:swp1"
    - "r2:et1"
  - endpoints:
    - "rr:swp2"
    - "r1:swp1"
  - endpoints:
    - "r1:swp2"
    - "servera:eth1"
  - endpoints:
    - "r2:et2"
    - "serverb:eth1"

