name: netsim-ceos-flowpec_a

topology:
  nodes:
    rr:
      kind: cvx
      image: networkop/cx:4.3.0
      group: as65000
      runtime: docker
      exec:
        - ip link set dev swp1 mtu 1500
      binds:
        - rr-frr-config-files/frr.conf:/etc/frr/frr.conf
        - rr-exabgp-files/exabgp.conf:/exabgp.conf
        - rr-exabgp-files/routes.py:/routes.py
    r1:
      kind: ceos
      image: ceos:4.27.3F
      group: as65001
      env: {'INTFTYPE': 'et'}
      exec:
        - ip link set dev swp1 mtu 1500
    r2:
      kind: ceos
      image: ceos:4.27.3F
      group: as65002
      env: {'INTFTYPE': 'et'}
    r3:
      kind: ceos
      image: ceos:4.27.3F
      group: as65003
      env: {'INTFTYPE': 'et'}
    servera:
      kind: linux
      image: alpine
      group:
      exec:
        - ip link set dev eth1 mtu 1500
        - ip route delete default via 172.20.20.1 dev eth0
        - ip address add 172.16.0.2/24 dev eth1
        - ip route add 0.0.0.0/0 via 172.16.0.3 dev eth1
    serverb:
      kind: linux
      image: alpine
      group: 
      exec:
        - ip link set dev eth1 mtu 1500
        - ip route delete default via 172.20.20.1 dev eth0
        - ip address add 172.16.1.2/24 dev eth1
        - ip route add 0.0.0.0/0 via 172.16.1.3 dev eth1
  links:
  - endpoints:
    - "r1:et1"
    - "r3:et1"
  - endpoints:
    - "r2:et1"
    - "r3:et2"
  - endpoints:
    - "rr:swp1"
    - "r3:et3"
  - endpoints:
    - "r1:et2"
    - "servera:eth1"
  - endpoints:
    - "r2:et2"
    - "serverb:eth1"

