name: netsim-ceos-flowpec_a

topology:
  nodes:
    rr:
      kind: cvx
      image: networkop/cx:4.3.0
      group: as65000
      runtime: docker
    r1:
      kind: cvx
      image: networkop/cx:4.3.0
      group: as65001
      runtime: docker
    r2:
      kind: ceos
      image: ceos:4.27.3F
      group: as65002
      env: {'INTFTYPE': 'et'}
    servera:
      kind: linux
      image: alpine
      group: 
    serverb:
      kind: linux
      image: alpine
      group: 


  links:
  - endpoints:
    - "rr:swp1"
    - "r2:et1"
  - endpoints:
    - "rr:swp2"
    - "r1:swp1"
  - endpoints:
    - "r1:swp2"
    - "servera:eth1"
  - endpoints:
    - "r2:et2"
    - "serverb:eth1"

