# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
as65000:
  hosts:
    rr: {}
as65001:
  hosts:
    r1: {}
    r4: {}
    r5: {}
    r6: {}
as65002:
  hosts:
    r2: {}
as65003:
  hosts:
    r3: {}
cumulus:
  hosts:
    rr:
      ansible_host: clab-netsim-ceos-flowpec_a-rr
      id: 1
eos:
  hosts:
    ixp:
      ansible_host: clab-netsim-ceos-flowpec_a-ixp
      id: 2
    r1:
      ansible_host: clab-netsim-ceos-flowpec_a-r1
      id: 3
    r2:
      ansible_host: clab-netsim-ceos-flowpec_a-r2
      id: 4
    r3:
      ansible_host: clab-netsim-ceos-flowpec_a-r3
      id: 5
    r4:
      ansible_host: clab-netsim-ceos-flowpec_a-r4
      id: 6
    r5:
      ansible_host: clab-netsim-ceos-flowpec_a-r5
      id: 7
    r6:
      ansible_host: clab-netsim-ceos-flowpec_a-r6
      id: 8
linux:
  hosts:
    servera:
      ansible_host: clab-netsim-ceos-flowpec_a-servera
      id: 9
    serverb:
      ansible_host: clab-netsim-ceos-flowpec_a-serverb
      id: 10
    serverc:
      ansible_host: clab-netsim-ceos-flowpec_a-serverc
      id: 11
modules:
  hosts:
    ixp: {}
    r1: {}
    r2: {}
    r3: {}
    r4: {}
    r5: {}
    r6: {}
    rr: {}
    servera: {}
    serverb: {}
    serverc: {}
