# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
as65000:
  hosts:
    rr: {}
as65001:
  hosts:
    r1: {}
as65002:
  hosts:
    r2: {}
as65003:
  hosts:
    r3: {}
cumulus:
  hosts:
    rr:
      ansible_host: clab-netsim-ceos-flowpec_a-rr
      id: 1
eos:
  hosts:
    r1:
      ansible_host: clab-netsim-ceos-flowpec_a-r1
      id: 2
    r2:
      ansible_host: clab-netsim-ceos-flowpec_a-r2
      id: 3
    r3:
      ansible_host: clab-netsim-ceos-flowpec_a-r3
      id: 4
linux:
  hosts:
    servera:
      ansible_host: clab-netsim-ceos-flowpec_a-servera
      id: 5
    serverb:
      ansible_host: clab-netsim-ceos-flowpec_a-serverb
      id: 6
modules:
  hosts:
    r1: {}
    r2: {}
    r3: {}
    rr: {}
    servera: {}
    serverb: {}
