# Ansible inventory created from ['./topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
eos:
  hosts:
    ixp:
      ansible_host: clab-netsim-ceos-flowpec_a-ixp
      id: 2
    r1:
      ansible_host: clab-netsim-ceos-flowpec_a-r1
      id: 3
    r2:
      ansible_host: clab-netsim-ceos-flowpec_a-r2
      id: 4
    r3:
      ansible_host: clab-netsim-ceos-flowpec_a-r3
      id: 5
    rr:
      ansible_host: clab-netsim-ceos-flowpec_a-rr
      id: 1
linux:
  hosts:
    servera:
      ansible_host: clab-netsim-ceos-flowpec_a-servera
      id: 6
    serverb:
      ansible_host: clab-netsim-ceos-flowpec_a-serverb
      id: 7
    serverc:
      ansible_host: clab-netsim-ceos-flowpec_a-serverc
      id: 8
modules:
  hosts:
    ixp: {}
    r1: {}
    r2: {}
    r3: {}
    rr: {}
