# Ansible inventory created from ['./topology.yml', 'package:topology-defaults.yml']
#
---
box: ceos:4.25.1F
hostname: clab-netsim-ceos-mcast_a--sfc51
interface_name: eth%d
kind: ceos
links:
- ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.18/30
  linkindex: 5
  name: sfc51 -> dis51
  neighbors:
    dis51:
      ifname: Ethernet2
      ipv4: 10.1.0.17/30
  provider_ifname: eth1
  remote_id: 6
  remote_ifindex: 2
  type: p2p
- ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.42/30
  linkindex: 11
  name: sfc51 -> sfc01
  neighbors:
    sfc01:
      ifname: Ethernet2
      ipv4: 10.1.0.41/30
  provider_ifname: eth2
  remote_id: 3
  remote_ifindex: 2
  type: p2p
- ifindex: 3
  ifname: Ethernet3
  ipv4: 10.1.0.50/30
  linkindex: 13
  name: sfc51 -> ser03
  neighbors:
    ser03:
      ifname: Ethernet2
      ipv4: 10.1.0.49/30
  provider_ifname: eth3
  remote_id: 10
  remote_ifindex: 2
  type: p2p
loopback:
  ipv4: 10.0.0.4/32
mgmt:
  ifname: Management0
  ipv4: 192.168.121.104
  mac: 08-4F-A9-00-00-04
module:
- ospf
