---
- name: NAPALM Arista test1
  gather_facts: False
  ignore_unreachable: yes
  hosts: EOS
  
  tasks:
    - name: Collect and Save command outputs
      ansible.c.cli_command:
        command: "show inventory | json"
      register: command_output
      
    - name: Print result
      debug:
        msg: "{{command_output.stdout}}"
