---
- name: Access to json file parts. Source file is in this same dir
  hosts: localhost
  vars:
    input0: "{{ lookup('file','testfile.json') | from_json }}"
    input1: "{{ input0.msg }}"
# This extracts certain all key values from multiple entries deep in the json structure 
  # tasks:
  #   - name: Create dictionary
  #     set_fact:
  #       interfaces: "{{ input.msg | json_query('*.macaddress') }}"
  #    - name: Print result
  #     debug:
  #       var: interfaces
# For each entry, shows the value of one field with the condition of another field
#   tasks:
#     - name: filter
#       debug:
#         msg: "{{ input.msg | json_query(query) }}"
#       vars:
#         index_var: 'DD=LDZLS24P,DI=prd2'
#         query: "[?description=='{{ index_var }}'].macaddress"


# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-items
  tasks:
    - name: show elements with lookup
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ input1 | json_query('*.macaddress')}}"
