---
- name: Access to json file parts. Source file is in this same dir
  hosts: localhost
  gather_facts: False
  vars:
    users:
      alice:
        name: Alice Appleworth
        telephone: 123-456-7890
      bob:
        name: Bob Bananarama
        telephone: 987-654-3210

  tasks:
    # with predefined vars
    - name: Print phone records
      debug:
        msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
      loop: "{{ lookup('dict', users) }}"
      
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-items
  # tasks:
  #   - name: Call a task looping the payload
  #     ansible.builtin.debug:
  #       msg: "{{ item.description }}"
  #     loop: "{{ msg_payload }}"
