# Ansible inventory created from ['./topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
box: ceos:4.25.1F
clab:
  kind: ceos
hostname: clab-netsim-ceos-mpls_a-c21
interfaces:
- clab:
    name: eth1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.29/30
  linkindex: 8
  name: c21 -> pe2
  neighbors:
  - ifname: Ethernet3
    ipv4: 10.1.0.30/30
    node: pe2
  remote_id: 4
  remote_ifindex: 3
  type: p2p
- clab:
    name: eth2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.45/30
  linkindex: 12
  name: c21 -> red2
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.46/30
    node: red2
  remote_id: 11
  remote_ifindex: 1
  type: p2p
loopback:
  ipv4: 10.0.0.8/32
mgmt:
  ifname: Management0
  ipv4: 192.168.121.108
  mac: 08-4F-A9-00-00-08
module: []
