# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
as65000:
  hosts:
    rr: {}
as65001:
  hosts:
    r1: {}
as65002:
  hosts:
    r2: {}
cumulus:
  hosts:
    r1:
      ansible_host: clab-netsim-ceos-flowpec_b-r1
      id: 2
    rr:
      ansible_host: clab-netsim-ceos-flowpec_b-rr
      id: 1
eos:
  hosts:
    r2:
      ansible_host: clab-netsim-ceos-flowpec_b-r2
      id: 3
linux:
  hosts:
    servera:
      ansible_host: clab-netsim-ceos-flowpec_b-servera
      id: 4
    serverb:
      ansible_host: clab-netsim-ceos-flowpec_b-serverb
      id: 5
modules:
  hosts:
    r1: {}
    r2: {}
    rr: {}
    servera: {}
    serverb: {}
