# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
box: arista/veos
interfaces:
- ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.46/30
  linkindex: 12
  name: ser01 -> edz
  neighbors:
  - ifname: Ethernet3
    ipv4: 10.1.0.45/30
    node: edz
  remote_id: 7
  remote_ifindex: 3
  type: p2p
loopback:
  ipv4: 10.0.0.8/32
mgmt:
  ifname: Management1
  ipv4: 192.168.121.108
  mac: 08-4F-A9-00-00-08
