# Ansible inventory created from ['./topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
as65000:
  hosts:
    pe1: {}
    pe2: {}
    rr1: {}
    rr2: {}
as65001:
  hosts:
    x1: {}
eos:
  hosts:
    c11:
      ansible_host: clab-netsim-ceos-bgp_a-c11
      id: 6
    c12:
      ansible_host: clab-netsim-ceos-bgp_a-c12
      id: 7
    c21:
      ansible_host: clab-netsim-ceos-bgp_a-c21
      id: 8
    cx1:
      ansible_host: clab-netsim-ceos-bgp_a-cx1
      id: 9
    pe1:
      ansible_host: clab-netsim-ceos-bgp_a-pe1
      id: 3
    pe2:
      ansible_host: clab-netsim-ceos-bgp_a-pe2
      id: 4
    rr1:
      ansible_host: clab-netsim-ceos-bgp_a-rr1
      id: 1
    rr2:
      ansible_host: clab-netsim-ceos-bgp_a-rr2
      id: 2
    x1:
      ansible_host: clab-netsim-ceos-bgp_a-x1
      id: 5
