# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
cumulus:
  hosts:
    dis01:
      ansible_host: 192.168.121.105
      id: 5
    dis51:
      ansible_host: 192.168.121.106
      id: 6
    edz:
      ansible_host: 192.168.121.107
      id: 7
    ser01:
      ansible_host: 192.168.121.108
      id: 8
    ser02:
      ansible_host: 192.168.121.109
      id: 9
    ser03:
      ansible_host: 192.168.121.110
      id: 10
    sfc01:
      ansible_host: 192.168.121.103
      id: 3
    sfc51:
      ansible_host: 192.168.121.104
      id: 4
    sfp01:
      ansible_host: 192.168.121.101
      id: 1
    sfp51:
      ansible_host: 192.168.121.102
      id: 2
