# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
bgp:
  advertise_loopback: false
  as: 65000
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65000
    ipv4: 10.0.0.1
    name: rr1
    rr: true
    type: ibgp
  - as: 65000
    ipv4: 10.0.0.3
    name: pe1
    type: ibgp
  - as: 65000
    ipv4: 10.0.0.4
    name: pe2
    type: ibgp
  next_hop_self: true
  router_id: 10.0.0.2
  rr: true
  rr_cluster_id: 10.0.0.1
box: arista/veos
interfaces:
- ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.10/30
  linkindex: 3
  name: rr2 -> pe1
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.9/30
    node: pe1
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  remote_id: 3
  remote_ifindex: 2
  type: p2p
- ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.14/30
  linkindex: 4
  name: rr2 -> pe2
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.13/30
    node: pe2
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  remote_id: 4
  remote_ifindex: 2
  type: p2p
loopback:
  ipv4: 10.0.0.2/32
mgmt:
  ifname: Management1
  ipv4: 192.168.121.102
  mac: 08-4F-A9-00-00-02
module:
- ospf
- bgp
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.2
