# Ansible inventory created from ['/home/jaime/netsim-labs/netsim-veos-mpls/topology.yml', 'package:topology-defaults.yml']
#

ansible_connection: network_cli
ansible_network_os: eos
ansible_ssh_pass: vagrant
ansible_user: vagrant
