# Ansible inventory created from ['./topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
as65001:
  hosts:
    A: {}
    B: {}
as65002:
  hosts:
    C: {}
    D: {}
    E: {}
    F: {}
    G: {}
custom_configs:
  hosts: {}
eos:
  hosts:
    A:
      ansible_host: clab-simple2-A
      id: 1
    B:
      ansible_host: clab-simple2-B
      id: 2
    C:
      ansible_host: clab-simple2-C
      id: 3
    D:
      ansible_host: clab-simple2-D
      id: 4
    E:
      ansible_host: clab-simple2-E
      id: 5
    F:
      ansible_host: clab-simple2-F
      id: 6
    G:
      ansible_host: clab-simple2-G
      id: 7
modules:
  hosts:
    A: {}
    B: {}
    C: {}
    D: {}
    E: {}
    F: {}
    G: {}
