# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
box: CumulusCommunity/cumulus-vx
links:
- ifindex: 1
  ifname: swp1
  ipv4: 10.1.0.45/30
  linkindex: 12
  name: ser03 -> sfc01
  neighbors:
    sfc01:
      ifname: swp3
      ipv4: 10.1.0.46/30
  remote_id: 3
  remote_ifindex: 3
  type: p2p
- ifindex: 2
  ifname: swp2
  ipv4: 10.1.0.49/30
  linkindex: 13
  name: ser03 -> sfc51
  neighbors:
    sfc51:
      ifname: swp3
      ipv4: 10.1.0.50/30
  remote_id: 4
  remote_ifindex: 3
  type: p2p
loopback:
  ipv4: 10.0.0.10/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.110
  mac: 08-4F-A9-00-00-0A
