# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
eos:
  hosts:
    edz:
      ansible_host: 192.168.121.102
      id: 2
    sfp01:
      ansible_host: 192.168.121.101
      id: 1
