# MKDOCS navigation structure and configuration
---
site_name: BGP Labs
docs_dir: docs
site_dir: _html
repo_url: https://github.com/bgplab/bgplab
site_url: https://bgplabs.net/
site_description: Hands-on BGP labs using virtual devices
site_author: Ivan Pepelnjak, ipSpace.net AG
copyright: (C) 2023–2024 Ivan Pepelnjak (ipSpace.net AG)
plugins:
- search
- include_dir_to_nav
nav:
- Home:
  - index.md
  - 2-labs-by-technology.md
  - "Upcoming Labs": 3-upcoming.md
  - 99-about.md
- Installation:
  - 1-setup.md
  - "Custom Lab Infrastructure":
    - external/index.md
    - external/4-router.md
- "Deploy BGP":
  - Overview: basic/index.md
  - "Setting Up BGP":
    - basic/0-frrouting.md
    - basic/1-session.md
    - basic/2-multihomed.md
    - basic/3-originate.md
    - basic/4-ipv6.md
    - basic/5-redistribute.md
  - "Protecting BGP Sessions":
    - "MD5 Passwords and GTSM": basic/6-protect.md
    - "TCP Autentication Option (TCP-AO)": basic/9-ao.md
    - "Limit the Number of Accepted BGP Prefixes": basic/b-max-prefix.md
  - "BGP in Larger Networks":
    - "Establish an IBGP Session": ibgp/1-edge.md
    - "Build a Transit Network with IBGP": ibgp/2-transit.md
    - "Use BGP Route Reflectors": ibgp/3-rr.md
    - session/6-templates.md
    - "BGP Policy Templates": session/7-policy.md
  - "Manipulate AS Path":
    - session/1-allowas_in.md
    - session/2-asoverride.md
    - session/3-localas.md
    - session/4-removeprivate.md
  - "Other Useful Topics":
    - basic/7-bfd.md
    - basic/8-aggregate.md
    - basic/c-default-route.md

- "Routing Policies":
  - Overview: policy/index.md
  - Route Filters:
    - policy/2-stop-transit.md
    - policy/3-prefix.md
    - policy/4-reduce.md
    - basic/b-max-prefix.md
  - "Outgoing (Egress) Traffic":
    - policy/1-weights.md
    - policy/5-local-preference.md
  - "Incoming (Ingress) Traffic":
    - policy/6-med.md
    - policy/7-prepend.md
    - policy/8-community-attach.md
  - "More Complex Routing Policies":
    - policy/9-community-use.md
    - policy/a-locpref-route-map.md
    - session/7-policy.md

- Challenges:
  - challenge/20-merge-as.md
  - challenge/04-block-fat-fingers.md

- "Upcoming":
  - Overview: 3-upcoming.md
  - challenge/02-no-export.md
  - challenge/03-graceful-shutdown.md
  - challenge/01-bird-rr.md
  - session/5-routeserver.md

markdown_extensions:
- footnotes
- abbr
- def_list
- admonition
- attr_list
- sane_lists
- smarty
- nl2br

theme:
  name: mkdocs
  custom_dir: _mkdocs_theme
  navigation_depth: 3
