# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65001
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65003
    ifindex: 1
    ipv4: 10.1.0.2
    name: r3
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.2
box: ceos:4.27.3F
clab:
  env:
    INTFTYPE: et
  kind: ceos
hostname: clab-netsim-ceos-flowpec_a-r1
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.1/30
  linkindex: 1
  name: r1 -> r3
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.2/30
    node: r3
  remote_id: 4
  remote_ifindex: 1
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: netsim-br_4
  clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 172.16.0.2/24
  linkindex: 4
  name: r1 -> [servera]
  neighbors:
  - ifname: eth1
    ipv4: 172.16.0.5/24
    node: servera
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: true
  role: stub
  type: lan
loopback:
  ipv4: 10.0.0.2/32
mgmt:
  ifname: Management0
  ipv4: 192.168.121.102
  mac: 08-4F-A9-00-00-02
module:
- ospf
- bgp
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.2
