# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
box: CumulusCommunity/cumulus-vx
links:
- ifindex: 1
  ifname: swp1
  ipv4: 10.1.0.1/30
  linkindex: 1
  name: dis01 -> sfc01
  neighbors:
    sfc01:
      ifname: swp1
      ipv4: 10.1.0.2/30
  remote_id: 3
  remote_ifindex: 1
  type: p2p
- ifindex: 2
  ifname: swp2
  ipv4: 10.1.0.5/30
  linkindex: 2
  name: dis01 -> dis51
  neighbors:
    dis51:
      ifname: swp1
      ipv4: 10.1.0.6/30
  remote_id: 6
  remote_ifindex: 1
  type: p2p
- ifindex: 3
  ifname: swp3
  ipv4: 10.1.0.9/30
  linkindex: 3
  name: dis01 -> edz
  neighbors:
    edz:
      ifname: swp1
      ipv4: 10.1.0.10/30
  remote_id: 7
  remote_ifindex: 1
  type: p2p
- ifindex: 4
  ifname: swp4
  ipv4: 10.1.0.13/30
  linkindex: 4
  name: dis01 -> sfp01
  neighbors:
    sfp01:
      ifname: swp1
      ipv4: 10.1.0.14/30
  remote_id: 1
  remote_ifindex: 1
  type: p2p
loopback:
  ipv4: 10.0.0.5/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.105
  mac: 08-4F-A9-00-00-05
module:
- ospf
